---
title: "Pre-process_DSF"
author: '39582833'
date: "2025-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load the necessary library
library(dplyr)
library(knitr)
library(ggplot2)
library(caret)
```


```{r}
# Load the datasets for the three branches
data1  <- read.csv("Branch1.csv")
data2  <- read.csv("Branch2.csv")
data3  <- read.csv("Branch3.csv")

```



```{r}
#  Add feature column Source to indicate that the merged dataset is from a different dataset
data1$Source <- 1
data2$Source <- 2
data3$Source <- 3
```

```{r}
# Merge the three datasets into one
data <- rbind(data1, data2, data3)
```



```{r}
# View the structure of the merged dataset
str(data)
```


```{r}
# View the summary of the dataset
summary(data)
```
```{r}
# View the structure of the column 'Gender'
str(data$Gender)
```

```{r}
# Change the data type from character to number, Male is 1, Female is 0 
data$Gender <- ifelse(data$Gender == "Male", 1, 0)

```


```{r}
# View the structure of the changed column 'Gender'
str(data$Gender)
```


```{r}
# Missing-Value Handling

# Count the counts of rows that have 1 missing value at least
missing_rows <- sum(!complete.cases(data))  
# Count the total number of rows in the dataset
total_rows <- nrow(data) 
# Calculate the ratio of missing value rows to the total number of rows
missing_percentage <- (missing_rows / total_rows) * 100  
# Print the result
print(paste("The counts of missing-value columns:", missing_rows))
print(paste("The percentage of missing-value columns:", round(missing_percentage, 2), "%"))


```


```{r}
# Draw a pie chart to visualize the proportion between missing rows and total rows

# Create the data from 
pie_data <- c(missing_rows, total_rows - missing_rows)  
names(pie_data) <- c("Missing Rows", "Non-Missing Rows")  

# Create lable to show counts and percentage
labels <- c(
  paste("Missing Rows\n", missing_rows, " (", round(missing_percentage, 2), "%)"),
  paste("Non-Missing Rows\n", total_rows - missing_rows, " (", round(100 - missing_percentage, 2), "%)")
)

# Plot a pie chart
pie(pie_data, labels = labels, col = c("orangered", "steelblue1"), main = "Missing vs. Non-Missing Rows")
```

```{r}
# Remove rows with missing value from the dataset
data <- na.omit(data)
```

```{r}
# Verify that missing values are removed successfully

# Count the counts of rows that have 1 missing value at least
missing_rows <- sum(!complete.cases(data))  
print(paste("The counts of missing-value columns:", missing_rows))

```


```{r}
# Calculate the number of duplicated rows 
sum(duplicated(data))
```



```{r}
# Show the duplicated rows
duplicate_rows <- data[duplicated(data), ]
print(duplicate_rows)
```

```{r}
# Count the duplicateds for each row 
duplicate_counts <- data %>%
  group_by_all() %>%  
  filter(n() > 1) %>%  
  summarise(count = n(), .groups = 'drop')  

print(duplicate_counts)
```




```{r}
# Remove duplicate rows( only keep one)
data <- data[!duplicated(data), ]
```


```{r}
# Verify that remove duplicate rows successfully
sum(duplicated(data)) 
```

```{r}
# Plot a bar chart for gender distribution
ggplot(data, aes(x = factor(Gender))) +
  geom_bar(fill = "steelblue1") +
  labs(title = "Gender Distribution",
       x = "Gender",
       y = "Count") +
  theme_minimal() +
  scale_x_discrete(labels = c("0" = "Female", "1" = "Male"))+
  theme(plot.title = element_text(hjust = 0.5))
```



```{r}
# Plot a bar chart for Age distribution grouped in 5-year intervals

ggplot(data, aes(x = cut(Age, breaks = seq(0, max(data$Age) + 5, by = 5), right = FALSE))) +
  geom_bar(fill = "steelblue1", color = "black") +
  labs(title = "Age Distribution (5-year intervals)",
       x = "Age Group",
       y = "Count") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

```
```{r}
# Plot a histogram of scores with a kernel density curve
breaks <- nclass.Sturges(data$Score)
hist(data$Score, probability = TRUE, breaks = breaks, main = "Score Distribution", col = "steelblue1")
lines(density(data$Score, na.rm = TRUE), col = "orangered", lwd = 2)
```


```{r}
# Detect outliers based on business rules(scores below 350 or above 850)
lower_limit <- 350
upper_limit <- 850

# Detect outliers
outliers_business <- data$Score[data$Score < lower_limit | data$Score > upper_limit]
# Count the number of outliers
outliers_business_count <- length(outliers_business)

cat("Number of outliers (based on business rules):", outliers_business_count, "\n")
print(outliers_business)
```
```{r}
# Create a table with indices and scores of outliers
outliers_table <- data.frame(
  Index = which(data$Score < lower_limit | data$Score > upper_limit),
  Score = data$Score[data$Score < lower_limit | data$Score > upper_limit]
)

# Print the outliers table

print(outliers_table)
```

```{r}
# Total number of rows in the dataset
total_count <- nrow(data)

pie_data <- c(count_above_850, total_count - count_above_850)
names(pie_data) <- c("Outliers", "Regular Values")

# Calculate the percentage
percentage_above_850 <- round((count_above_850 / total_count) * 100, 2)
percentage_below_850 <- round((1 - count_above_850 / total_count) * 100, 2)

# Create lable to show counts and percentage
labels <- c(paste("Outliers\n", count_above_850, " (", percentage_above_850, "%)"),
            paste("Regular Values\n", total_count - count_above_850, " (", percentage_below_850, "%)"))

# plot a pie chart
pie(pie_data, labels = labels, col = c("orangered", "steelblue1"), main = "Outliers vs. Regular Values")
```

```{r}
# Remove outliers
data <- subset(data, Score >= lower_limit & Score <= upper_limit)
```


```{r}
# Verify that remove outliers successfully
outliers_business <- data$Score[data$Score < lower_limit | data$Score > upper_limit]
outliers_business_count <- length(outliers_business)

cat("Number of outliers (based on business rules):", outliers_business_count, "\n")
print(outliers_business)
```
```{r}
# Plot a histogram of scores with a kernel density curve
breaks <- nclass.Sturges(data$Score)  # 
hist(data$Score, probability = TRUE, breaks = breaks, main = "Score Distribution (After)", col = "steelblue1")
lines(density(data$Score, na.rm = TRUE), col = "orangered", lwd = 2)
```





```{r}
# Plot a bar plot of Tenure distribution
ggplot(data, aes(x = factor(Tenure))) +
  geom_bar(fill = "steelblue1") +
  labs(title = "Tenure Distribution",
       x = "Tenure",
       y = "Count") +
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))

```


```{r}
# Plot a histogram of Salary with a kernel density curve
breaks <- nclass.Sturges(data$Salary)  
hist(data$Salary, probability = TRUE, breaks = breaks, main = "Salary Distribution", col = "steelblue1")
lines(density(data$Salary, na.rm = TRUE), col = "orangered", lwd = 2)
```
```{r}
# Calculate the IQR of Salary
Q1_salary <- quantile(data$Salary, 0.25, na.rm = TRUE)  
Q3_salary <- quantile(data$Salary, 0.75, na.rm = TRUE)  
IQR_salary <- Q3_salary - Q1_salary  

# Calculate the outlier range for Salary
lower_bound_salary <- Q1_salary - 1.5 * IQR_salary
upper_bound_salary <- Q3_salary + 1.5 * IQR_salary

# Identify outliers in Salary
outliers_salary <- data$Salary[data$Salary < lower_bound_salary | data$Salary > upper_bound_salary]
cat("Salary outliers:", outliers_salary, "\n")

```

```{r}
# Plot a boxplot of Salary distribution and highlight outliers
ggplot(data, aes(y = Salary)) +
  geom_boxplot(fill = "steelblue1", outlier.color = "orangered", outlier.shape = 16, outlier.size = 2) +
  labs(title = "Salary Distribution with Outliers",
       y = "Salary") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) 
```


```{r}
# Remove outliers
data <- data[data$Salary >= lower_bound_salary & data$Salary <= upper_bound_salary, ]

```


```{r}
# Plot a histogram of Salary with a kernel density curve
breaks <- nclass.Sturges(data$Salary)  
hist(data$Salary, probability = TRUE, breaks = breaks, main = "Salary Distribution(After)", col = "steelblue1")
lines(density(data$Salary, na.rm = TRUE), col = "orangered", lwd = 2)

```
```{r}
# Select the data that is below 500
low_salary_data <- data[data$Salary < 500, ]

# Plot a histogram of Salary with a kernel density curve
breaks <- nclass.Sturges(low_salary_data$Salary)
hist(low_salary_data$Salary, probability = TRUE, breaks = breaks, main = "Salary Distribution(After)", col = "steelblue1")
lines(density(low_salary_data$Salary, na.rm = TRUE), col = "orangered", lwd = 2)
```






```{r}
# Plot a boxplot of Salary distribution and highlight outliers
ggplot(data, aes(y = Salary)) +
  geom_boxplot(fill = "steelblue1", outlier.color = "tan1", outlier.shape = 16, outlier.size = 2) +
  labs(title = "Salary Distribution with Outliers",
       y = "Salary") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) 
```





```{r}
# Plot a histogram of Balance with a kernel density curve
breaks <- nclass.Sturges(data$Balance)
hist(data$Balance, probability = TRUE, breaks = breaks, main = "Balance Distribution", col = "steelblue1")
lines(density(data$Balance, na.rm = TRUE), col = "orangered", lwd = 2)
```
```{r}
# Plot a bar chart for Products_in_Use distribution 
ggplot(data, aes(x = factor(Products_in_Use))) +
  geom_bar(fill = "steelblue1") +
  labs(title = "Products in Use Distribution",
       x = "Products in Use",
       y = "Count") +
  theme_minimal()+
  theme(plot.title = element_text(hjust = 0.5))
```






```{r}
# Calculate the IQR of Salary
Q1_balance <- quantile(data$Balance, 0.25, na.rm = TRUE)  
Q3_balance <- quantile(data$Balance, 0.75, na.rm = TRUE)  
IQR_balance <- Q3_balance - Q1_balance  

# Calculate the outlier range for Balance
lower_bound_balance <- Q1_balance - 1.5 * IQR_balance
upper_bound_balance <- Q3_balance + 1.5 * IQR_balance

# Finding outliers in Balance
outliers_balance <- data$Balance[data$Balance < lower_bound_balance | data$Balance > upper_bound_balance]
cat("Balance outliers:", outliers_balance, "\n")

```






```{r}
# View the modified dataset structure
str(data)
```





```{r}
# Display the summary of modified dataset
summary(data)
```


```{r}
base_name <- "output.csv"

# Specify the save path
output_path <- "output/"

# Check if the path exists, and create it if it doesn't
if (!dir.exists(output_path)) {
  dir.create(output_path, recursive = TRUE)
}

output_file <- paste0(output_path, base_name)

# Save the modified dataset to a CSV file and overwrite the file that has the same name
write.csv(data, file = output_file, row.names = FALSE, quote = FALSE)

cat("The file is saved:", output_file, "\n")
```


























